Submitting solution
cody-berry/leetcode pull request #6
Opened 2023-06-05 20:28 UTC by cody-berry

This is one of the worst solutions I've ever wrote. But it'll do.

2023-06-06 03:51 UTC, aeruru commented on 2697. Lexicographically Smallest Palindrome/solution.py
> +        if (len(s) % 2 == 1):
I think you probably could have simplified all of this logic with the integer divide operator (//)

2023-06-06 03:54 UTC, aeruru commented on 2697. Lexicographically Smallest Palindrome/solution.py
> +                changedString = (changedString[:firstIndex] + smallestLetter +
This code is pretty bad and super inefficient as you create a new string with every modification. Do you remember the technique I used in my first solution to the first problem in this contest?

2023-06-06 03:55 UTC, aeruru requested changes
I think you can do better so requesting changes :)

2023-06-06 19:28 UTC, merged

2023-06-11 17:35 UTC, winry-fruitiwi commented on 2697. Lexicographically Smallest Palindrome/solution.py
>                  # Make the letter with the bigger code the one with the smaller code.
What is "code"? Is it the ord?

2023-06-11 17:36 UTC, winry-fruitiwi commented on 2697. Lexicographically Smallest Palindrome/solution.py
> +                changedString = f"{changedString[:firstIndex]} + smallestLetter + {changedString[(firstIndex+1):lastIndex]} + smallestLetter + {changedString[(lastIndex+1):]}"
I can't understand this, unfortunately. I think you should explain this a bit better.

2023-06-11 17:37 UTC, winry-fruitiwi reviewed
Overall, I think your code is a bit messy and poorly documented.